### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [vitobotta/zsh-history-sync#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by vitobotta** [comment]
Hi @unixorn - I just added the MIT license. Is it OK now? Not sure when you first checked the repo but I switched from using Dropbox/similar to using a private Git repo since the syncing is more reliable.

Also thanks for sharing that tool, I hadn't come across it before and it looks handy!

**Comment by unixorn** [comment]
Yes, that's all I needed. I've been trying to only add plugins/themes/etc with licenses to the list. I don't much care _what_ license, just that there be a license so people working with license constraints can tell if they're able to use things.

I saw it on hangops and wanted to get it added :-)

**Comment by vitobotta** [comment]
@unixorn FYI I added encryption now :)

**Comment by unixorn** [comment]
Nice!
